# Generated by Django 5.2.3 on 2025-06-25 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteCAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIAPE_agente', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='Matrícula do Agente')),
                ('cpf_agente', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='CPF do Agente')),
                ('nome_agente', models.CharField(max_length=100, verbose_name='Nome do Agente')),
                ('data_nascimento_agente', models.DateField(verbose_name='Data de Nascimento')),
                ('status_agente', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('rg_agente', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Apenas números são permitidos.')], verbose_name='RG do Agente')),
                ('email_agente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Agente')),
                ('cargo_agente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Agente CAE',
                'verbose_name_plural': 'Agentes CAE',
            },
        ),
    ]
